function [ode_t, ode_simdata, ode_names] = ODE_4D_GRN(Mobj)
%A function to simulate an ODE model of a 4D GRN based on an input model
%object, which can be generated by model_4D_GRN(inputs)
%   Inputs:
%       inputs = {molA,molB,molC,molD,mola,molb,molc,mold,g0,g1,k,hr,fr,ha,fa}
%       molA, molB, molC, molD; Number of molecules of unbound promoters A - D
%       mola, molb, molc, mold; Number of molecules of proteins a - d
%       g0; Rate parameter of unactivated protein production
%       g1; Rate parameter of activated protein production
%       k; Protein degradation rate
%       hr; Rate parameter of repressor binding
%       fr; Rate parameter of repressor unbinding
%       ha; Rate parameter of activator binding
%       fa; Rate parameter of activator unbinding

%simulate model deterministically
configset = getconfigset(Mobj);
configset.CompileOptions.DimensionalAnalysis = true;
configset.SolverType = 'ode15s';
configset.StopTime = 1000000;
solver = configset.SolverOptions;
set(configset.SolverOptions, 'AbsoluteTolerance', 1.0e-8);

%do sim
[ode_t, ode_simdata, ode_names] = sbiosimulate(Mobj);
%plot(ode_t, ode_simdata(:,[2,7,12,17]), ':', 'LineWidth', 3)
end