function [ssa_t, ssa_simdata, ssa_names] = SSA_4D_GRN(Mobj)
%A function to simulate a stochastic model of a 4D GRN based on an input model
%object, which can be generated by model_4D_GRN(inputs)
%   Inputs:
%       inputs = {molA,molB,molC,molD,mola,molb,molc,mold,g0,g1,k,hr,fr,ha,fa}
%       molA, molB, molC, molD; Number of molecules of unbound promoters A - D
%       mola, molb, molc, mold; Number of molecules of proteins a - d
%       g0; Rate parameter of unactivated protein production
%       g1; Rate parameter of activated protein production
%       k; Protein degradation rate
%       hr; Rate parameter of repressor binding
%       fr; Rate parameter of repressor unbinding
%       ha; Rate parameter of activator binding
%       fa; Rate parameter of activator unbinding
    
%simulate model stochastically
configset = getconfigset(Mobj);
configset.CompileOptions.DimensionalAnalysis = true;
configset.SolverType = 'ssa';
configset.StopTime = 1000000;
solver = configset.SolverOptions;
solver.LogDecimation = 100;

%do sim
[ssa_t, ssa_simdata, ssa_names] = sbiosimulate(Mobj);
end

